# Generated by Django 5.1.3 on 2024-12-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fps', '0005_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
