# Generated by Django 5.1.3 on 2024-12-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fps', '0010_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание обязанностей'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Требования к кандидату'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название вакансии'),
        ),
    ]
