# Generated by Django 5.1.3 on 2024-12-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fps', '0011_remove_vacancy_responsibilities_vacancy_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Резюме')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Сопроводительное письмо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fps.vacancy')),
            ],
        ),
    ]
